name: Storage Deploy on GKE

on:
  workflow_run:
    workflows: ["Storage Build and Push"]
    types:
      - completed

jobs:

  CD:
    uses: storage-app-br/.github/.github/workflows/storage-deploy.yml@main
