name: Storage Build and Push

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  CI:
    uses: storage-app-br/.github/.github/workflows/storage-build.yml@main
    with:
      image_version: 0.1.${{ github.run_number }}