name: Storage Build and Push

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:

  CI:
    uses: storage-app-br/.github/.github/workflows/storage-build.yml@main
    with:
      image_version: "0.1.${{ github.run_number }}"
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}