name: Storage Build and Push

on:
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

jobs:

  CI:
    uses: uses: storage-app-br/.github/.github/workflows/storage-build.yml@main
