name: Storage Build and Push

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:

  CI:
    uses: storage-app-br/.github/.github/workflows/storage-build.yml@main
    env:
      IMAGE_VERSION: "0.1.${{github.run_number}}"