on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
    
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      GCP_SA_KEY:
        required: true
      GKE_CLUSTER_NAME:
        required: true
      GKE_ZONE:
        required: true
      GKE_PROJECT_ID:
        required: true

jobs:
  gke-deploy:
    runs-on: ubuntu-latest

    # environment:
    #   name: deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: setup-gke-gcloud-auth-plugin
        uses: simenandre/setup-gke-gcloud-auth-plugin@v1.1.2

      - name: kubeconfig
        run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GKE_PROJECT_ID }}

      - name: Clone gcp repository
        run: |
          git clone https://github.com/storage-app-br/gcp.git

      - name: Deploy to Kubernetes cluster in Another Repository
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            gcp/${{ secrets.GKE_PROJECT_ID }}/${{ secrets.GKE_CLUSTER_NAME }}/k8s/projects/storage-app/${{ vars.IMAGE_NAME }}/
          images: |
            docker.io/igorlage/${{ vars.IMAGE_NAME }}:${{  inputs.IMAGE_VERSION }}
